## Series

In [1]:
import pandas as pd
import numpy as np

In [2]:
l = [4,5,56,7]
l2 = pd.Series(l)
l2

0     4
1     5
2    56
3     7
dtype: int64

In [3]:
dic = {"a":[2,3,5],
       'b':5,
       'c':0
      }
s = pd.Series(dic)
s

a    [2, 3, 5]
b            5
c            0
dtype: object

In [4]:
s.size

3

In [5]:
s.shape

(3,)

In [6]:
s.info

<bound method Series.info of a    [2, 3, 5]
b            5
c            0
dtype: object>

In [7]:
print(s.dtype)

object


## Data_frame

### Creation

In [8]:
import numpy as np 
import pandas as pd

In [9]:
dic= {"A":[1,2,3,4,5],
      'B':[2,3,4,5,6],
      'C':[7,8,9,6,5],
      'D':[6,4,6,8,3],}

In [10]:
arr = np.array(list(dic.values()))
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [7, 8, 9, 6, 5],
       [6, 4, 6, 8, 3]])

In [11]:
df = pd.DataFrame(dic,index = ['x','y','z','x1',"y1"])
df

A  B  C  D
x   1  2  7  6
y   2  3  8  4
z   3  4  9  6
x1  4  5  6  8
y1  5  6  5  3

## Extraction

In [12]:
df['C']

x     7
y     8
z     9
x1    6
y1    5
Name: C, dtype: int64

In [13]:
df[df['C']>6]

A  B  C  D
x  1  2  7  6
y  2  3  8  4
z  3  4  9  6

### Modification

In [14]:
df['E'] = [2,5,7,8,9] # add a new columns 
df

A  B  C  D  E
x   1  2  7  6  2
y   2  3  8  4  5
z   3  4  9  6  7
x1  4  5  6  8  8
y1  5  6  5  3  9

In [15]:
df.loc['z1'] = [3,5,8,9,1] # add a row 
df

A  B  C  D  E
x   1  2  7  6  2
y   2  3  8  4  5
z   3  4  9  6  7
x1  4  5  6  8  8
y1  5  6  5  3  9
z1  3  5  8  9  1

In [16]:
df.drop(index = ['z1','x1'],columns = ['E','D']) # delete a row and columns 

A  B  C
x   1  2  7
y   2  3  8
z   3  4  9
y1  5  6  5

In [17]:
df.rename(index = {'x':'X',"y":'Y','z':'Z'},columns ={'A':'a','B':'b'} )
df# rename of rows and columns 

A  B  C  D  E
x   1  2  7  6  2
y   2  3  8  4  5
z   3  4  9  6  7
x1  4  5  6  8  8
y1  5  6  5  3  9
z1  3  5  8  9  1

In [18]:
df =df.set_index('A')

In [19]:
df

B  C  D  E
A            
1  2  7  6  2
2  3  8  4  5
3  4  9  6  7
4  5  6  8  8
5  6  5  3  9
3  5  8  9  1

In [20]:
df = df.reset_index()

In [21]:
df

A  B  C  D  E
0  1  2  7  6  2
1  2  3  8  4  5
2  3  4  9  6  7
3  4  5  6  8  8
4  5  6  5  3  9
5  3  5  8  9  1

## Data Exploration

In [22]:
df['A'].sort_values()

0    1
1    2
2    3
5    3
3    4
4    5
Name: A, dtype: int64

In [23]:
type(df)

pandas.core.frame.DataFrame

In [24]:
df.ndim

2

In [25]:
df.shape

(6, 5)

In [26]:
df.size

30

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       6 non-null      int64
 1   B       6 non-null      int64
 2   C       6 non-null      int64
 3   D       6 non-null      int64
 4   E       6 non-null      int64
dtypes: int64(5)
memory usage: 372.0 bytes


In [28]:
df.columns 

Index(['A', 'B', 'C', 'D', 'E'], dtype='object')

In [29]:
df.index

RangeIndex(start=0, stop=6, step=1)

df.keys()

In [30]:
df

A  B  C  D  E
0  1  2  7  6  2
1  2  3  8  4  5
2  3  4  9  6  7
3  4  5  6  8  8
4  5  6  5  3  9
5  3  5  8  9  1

### Other

### Transpose

In [31]:
data = [[12, 45, 67, 23, 89, 34, 90, 22],[2,3,4,6,7,5,3,8]] # transpose data frame
data = pd.DataFrame(data,index = ['x','y']).transpose()
data

x  y
0  12  2
1  45  3
2  67  4
3  23  6
4  89  7
5  34  5
6  90  3
7  22  8

In [32]:
df['A'].unique()

array([1, 2, 3, 4, 5], dtype=int64)

In [33]:
df['A'].sort_values()

0    1
1    2
2    3
5    3
3    4
4    5
Name: A, dtype: int64

In [34]:
df['A'].value_counts()

A
3    2
1    1
2    1
4    1
5    1
Name: count, dtype: int64

In [35]:
df['A'].to_list()

[1, 2, 3, 4, 5, 3]

In [36]:
df['A'].to_numpy()

array([1, 2, 3, 4, 5, 3], dtype=int64)

In [37]:
df['A'].isnull()

0    False
1    False
2    False
3    False
4    False
5    False
Name: A, dtype: bool

In [38]:
df['A'].isnull().sum()

0

#### Combining DataFrame

In [39]:
df1 = pd.DataFrame({'city':['mumbai','delhi','banglore','hydrabad'],
       'temp':[30,35,40,45]})
df1

city  temp
0    mumbai    30
1     delhi    35
2  banglore    40
3  hydrabad    45

In [40]:
df2 = pd.DataFrame({"city":['delhi','mumbai','banglore','chennai'],
      'humidity':[60,65,70,75]})
df2

city  humidity
0     delhi        60
1    mumbai        65
2  banglore        70
3   chennai        75

#### Concatination

In [41]:
pd.concat([df1,df2],ignore_index = True,axis = 0) # by default axis = 0

city  temp  humidity
0    mumbai  30.0       NaN
1     delhi  35.0       NaN
2  banglore  40.0       NaN
3  hydrabad  45.0       NaN
4     delhi   NaN      60.0
5    mumbai   NaN      65.0
6  banglore   NaN      70.0
7   chennai   NaN      75.0

In [42]:
pd.concat([df1,df2],axis = 1)

city  temp      city  humidity
0    mumbai    30     delhi        60
1     delhi    35    mumbai        65
2  banglore    40  banglore        70
3  hydrabad    45   chennai        75

#### Merge

In [43]:
left_df = pd.merge(df1,df2,how = 'left',on = 'city',)
left_df

city  temp  humidity
0    mumbai    30      65.0
1     delhi    35      60.0
2  banglore    40      70.0
3  hydrabad    45       NaN

In [44]:
right_merge = pd.merge(df1,df2,how = 'right', on = 'city')
right_merge

city  temp  humidity
0     delhi  35.0        60
1    mumbai  30.0        65
2  banglore  40.0        70
3   chennai   NaN        75

In [45]:
inner_merge = pd.merge(df1,df2,how = 'inner', on = 'city') # by default inner merge 
inner_merge

city  temp  humidity
0    mumbai    30        65
1     delhi    35        60
2  banglore    40        70

In [46]:
outer_merge = pd.merge(df1,df2,how = 'outer',on = 'city')
outer_merge

city  temp  humidity
0  banglore  40.0      70.0
1   chennai   NaN      75.0
2     delhi  35.0      60.0
3  hydrabad  45.0       NaN
4    mumbai  30.0      65.0

### Discritization- cut

In [47]:
data = [[12, 45, 67, 23, 89, 34, 90, 22],[2,3,4,6,7,5,3,8]] # transpose data frame
data = pd.DataFrame(data,index = ['x','y']).transpose()
data['Catego']= pd.cut(data['x'],
                         bins= [0, 20, 30, 50, 70, 90],
                         labels = ['a','b','c','d','e'])
print(data)

    x  y Catego
0  12  2      a
1  45  3      c
2  67  4      d
3  23  6      b
4  89  7      e
5  34  5      c
6  90  3      e
7  22  8      b


### Crosstab

#### pd.crosstab() Pandas library ka ek powerful function hai jo categorical data ka analysis karne ke liye use hota hai.
#### Isse hum contingency table bana sakte hain jo 2 ya usse zyada variables ke beech relationship ko summarize karta hai.

In [48]:
data = {
    'Restaurant': ['A', 'B', 'C', 'A', 'B', 'C', 'A', 'B', 'A', 'C'],
    'Cuisine': ['Indian', 'Chinese', 'Italian', 'Indian', 'Chinese', 'Italian', 
                'Indian', 'Chinese', 'Indian', 'Italian'],
    'Rating': [4, 5, 3, 4, 5, 4, 3, 5, 4, 3]
}
df = pd.DataFrame(data)
df

Restaurant  Cuisine  Rating
0          A   Indian       4
1          B  Chinese       5
2          C  Italian       3
3          A   Indian       4
4          B  Chinese       5
5          C  Italian       4
6          A   Indian       3
7          B  Chinese       5
8          A   Indian       4
9          C  Italian       3

In [49]:
pd.crosstab(index = df['Restaurant'],columns = df['Rating'],margins = True)

Rating      3  4  5  All
Restaurant              
A           1  3  0    4
B           0  0  3    3
C           2  1  0    3
All         3  4  3   10

In [50]:
data = {
    'Restaurant': ['A', 'B', 'C', 'A', 'B', 'C', 'A', 'B', 'A', 'C'],
    'Cuisine': ['Indian', 'Chinese', 'Italian', 'Indian', 'Chinese', 'Italian', 
                'Indian', 'Chinese', 'Indian', 'Italian'],
    'Rating': [4, 5, 3, 4, 5, 4, 3, 5, 4, 3],
    'Delivery': ['Yes', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'No', 'Yes', 'Yes']}
df = pd.DataFrame(data)
result = pd.crosstab(index=[df['Restaurant'], df['Delivery']],
                      columns=[df['Cuisine'], df['Rating']],
                      margins=True)
result

Cuisine             Chinese Indian    Italian    All
Rating                    5      3  4       3  4    
Restaurant Delivery                                 
A          No             0      1  0       0  0   1
           Yes            0      0  3       0  0   3
B          No             3      0  0       0  0   3
C          Yes            0      0  0       2  1   3
All                       3      1  3       2  1  10

## Grpupby

In [51]:
data = {
    'Restaurant': ['A', 'B', 'A', 'C', 'B', 'C', 'A', 'B', 'C', 'A'],
    'Cuisine': ['Indian', 'Chinese', 'Indian', 'Italian', 'Chinese', 'Italian',
                'Indian', 'Chinese', 'Italian', 'Indian'],
    'Rating': [4, 5, 3, 4, 5, 4, 3, 5, 3, 4],
    'Sales': [200, 150, 300, 400, 250, 350, 220, 180, 360, 290]
}
df = pd.DataFrame(data)
df

Restaurant  Cuisine  Rating  Sales
0          A   Indian       4    200
1          B  Chinese       5    150
2          A   Indian       3    300
3          C  Italian       4    400
4          B  Chinese       5    250
5          C  Italian       4    350
6          A   Indian       3    220
7          B  Chinese       5    180
8          C  Italian       3    360
9          A   Indian       4    290

In [56]:
df.groupby('Restaurant')['Sales'].mean()

Restaurant  Cuisine
A           Indian     252.500000
B           Chinese    193.333333
C           Italian    370.000000
Name: Sales, dtype: float64

In [57]:
df.groupby(['Restaurant','Cuisine'])['Sales'].mean()

Restaurant  Cuisine
A           Indian     252.500000
B           Chinese    193.333333
C           Italian    370.000000
Name: Sales, dtype: float64

In [ ]:
cat_perc = application_df[['REG_REGION_NOT_WORK_REGION', 'TARGET']].groupby(['REG_REGION_NOT_WORK_REGION'],as_index=False).mean() 

In [90]:
df2 = pd.DataFrame({'a':[9,8,7,5,7,7,55,99,44,7],
                    'b':[1,0,0,0,1,1,0,9,0,1]})
df2

a  b
0   9  1
1   8  0
2   7  0
3   5  0
4   7  1
5   7  1
6  55  0
7  99  9
8  44  0
9   7  1

In [114]:
df2[['a','b']].groupby(['a'],as_index = False).mean()

a     b
0   5  0.00
1   7  0.75
2   8  0.00
3   9  1.00
4  44  0.00
5  55  0.00
6  99  9.00